nextstrain/seasonal-flu

.gitignore, config/outliers_h1n1pdm.txt, config/outliers_h3n2.txt, config/outliers_yam.txt
Merge in additional outliers from dcd019c to run rebuilds.
=> Add outliers for rebuilds.

scripts/select_strains.py
Fixes a bug in the logic associated with filtering strains by date which was causing strains from outside requested time intervals to be included in the final output. This bug was due to an off-by-one error in parsing of months where metadata month values were zero-indexed and being compared to one-indexed months in datetime objects.
This commit addresses this error by filtering strains by numeric float dates at the beginning of the flu subsampling function. This approach allows users to specify time intervals to the day and have the subsampling respect that precise of a request whereas the previous implementation with the `cat_valid` function only checked the year and month of strains.
Note: the bug described here is only an issue when the `--time-interval` option is used to specify a …
=> Ensure no future sequences are included in builds

scripts/select_strains.py
This is an alternate implementation to the original flu subsampling code [1]
that provides options to specify a region to prefer viruses from and a fraction
of viruses per month that should be sampled from that region. The original
implementation could not be copied directly into the current script because this
script is itself a reimplementation of the original method.
Closes #20.
[1] https://github.com/nextstrain/augur/blob/4ed0024/builds/flu/flu_subsampling.py#L97-L128
=> Enable preferential sampling of specific regions in strain selection

Snakefile, Snakefile_WHO, Snakefile_base, Snakefile_countries, Snakefile_report, scripts/graph_frequencies.py, scripts/plot_titer_matrices.py, scripts/select_strains.py
This allows making builds for individual countries or groups of countries.
=> Country builds

batch.py
This implements new `--detach` feature available in the CLI. This shouldn't be merged until https://github.com/nextstrain/cli/pull/54 goes in.
=> Implement new --detach CLI feature in batch script

config/clades_h3n2_ha.tsv
The 193M mutation does not appear in the H3N2 12y tree for HA1, but it
does appear for HA2.
=> Update clade definition H3N2 3C.2a1b.2a

scripts/select_strains.py
Previously, the condition checked if the age string was exactly 'm'. Updated to check the last character.
_N/A_
Not sure how to test.
=> Fix age in months detection

config/clades-long_h3n2_ha.tsv, config/clades_h3n2_ha.tsv
In discussion with Dave, Becky, and Nicola, these seemed worth adding.
=> add additional h3n2 clades

config/reference_h3n2_na.gb
Update CDS coordinates to match the current record in GenBank and to resolve issue #98.
=> config/reference_h3n2_na: Update CDS coordinates

scripts/plot_titer_matrices.py, scripts/scores.py
Remove all references to the removed `select_strains` script so they don't raise a `ModuleNotFoundError`.
=> Remove `select-strains` references

profiles/private.nextflu.org/export.smk
Follow up on https://github.com/nextstrain/seasonal-flu/pull/119. 
See f9a06aadedebd045bb8081f0355ef521863b3f42 commit message for details.
=> private.nextflu.org/export: Remove translate rule output

.github/workflows/ci.yaml
Trim back CI jobs for reasons stated in
https://github.com/nextstrain/cli/commit/fab709a2f45fc74afe2a15038e877e4dd58ae222
Following https://github.com/nextstrain/monkeypox/pull/176
=> CI: Update workflow triggers

profiles/nextflu-private/antigenic_distances.smk, profiles/private.nextflu.org/export.smk, workflow/snakemake_rules/core.smk, workflow/snakemake_rules/fitness.smk, workflow/snakemake_rules/titer_models.smk
port to nextclade 3 and use more sensible file names for translations
=> Nextclade3 update

workflow/envs/nextstrain.yaml
Replace `nextalign` with `nextclade` the workflow
has been updated to use Nextclade V3 in
https://github.com/nextstrain/seasonal-flu/pull/145
=> nextstrain.yaml: Update to Nextclade v3

workflow/snakemake_rules/select_strains.smk
Follow up to <https://github.com/nextstrain/seasonal-flu/pull/198#discussion_r1888998308>
=> annotate_metadata_with_gihsn: mark output as `temp()`

scripts/calculate_epiweek.py, scripts/plot_antigenic_distances_between_strains.py
`augur.utils.read_strains` has been moved to `augur.io.read_strains` and deprecated for over a year.
It will be completely removed soon
<https://github.com/nextstrain/augur/issues/1747>
=> Update use of `augur.utils.read_strains` to `augur.io.read_strains`

ingest/build-configs/manual-upload/README.md, ingest/build-configs/manual-upload/Snakefile
Support running with `nextstrain run` by using a potential custom configuration file from the analysis directory.
Includes instructions on how to run the workflow with `nextstrain run`.
=> ingest/manual-upload: support `nextstrain run`

README.md, profiles/gisaid/builds.yaml
Documenting some sharp edges prompted by https://github.com/nextstrain/seasonal-flu/issues/230 and discussion on 
[Slack](https://bedfordlab.slack.com/archives/C03KWDET9/p1748020608566979).
=> Update GISAID quickstart docs

ingest/README.md, ingest/build-configs/manual-upload/README.md, ingest/build-configs/nextstrain-automation/README.md
These notes helped me when reading through this work for the first time
It'd also be a good idea for us to document the process around re-processing everything (delete the cache & move processed to unprocessed, I think?)
=> Add overview info to ingest READMEs

CHANGES.md, profiles/gisaid/builds.yaml, profiles/gisaid/prepare_data.smk, scripts/xls2csv.py
Fixes several issues with parsing of GISAID metadata and sequences that appeared when I tried to run the quickstart guide with the workflow changes in #240.
Depends on #240
=> Fix GISAID data parsing for quickstart
