nextstrain/seasonal-flu

Snakefile, config/auspice_config.json
Passes a tree to the titer substitition model to add a "nodes" attribute to the
JSON output with antigenic advance values per node. Additionally, adds the
resulting JSON to the default inputs for auspice export and adds a corresponding
auspice color-by configuration for "cTiterSub".
Relies on code from the corresponding `ctitersub-tree` branch of augur.
Resolves #4.
=> Annotate tree nodes with titer substitution model

Snakefile, config/auspice_config.json, config/frequency_weights_by_region.json
Addressing issue #3, this PR modifies auspice configuration to hide the map and show the frequencies panel and uses the KDE frequencies method to estimate region-weighted frequencies from
the refined tree.
=> Build tip frequencies for auspice

Snakefile, scripts/extract_sequences.py, scripts/select_strains.py
Adds a new filter rule that applies the augur filter command to omit sequences
shorter than a minimum length, outliers, and samples with missing geographic
metadata prior to strain selection, in an attempt to match the filtering
requirements used by previous augur builds [1]. This commit also updates
`select_strains.py` to accept one or more FASTA files and to only consider
metadata for samples whose sequences made it through the aforementioned
filters. After strains are selected, we still need a rule to extract the segment
sequences corresponding to each strain. This rule has been renamed from "filter"
to "extract" and its body has been replaced with a call to a standalone script
that performs the extraction using the same logic as the original Python code.
On a related note, this commit …
=> Align sample filtering requirements with previous augur builds

Snakefile, scripts/select_strains.py
@rneher ---
I noticed that the existing `subsampling.py` was behaving strangely with regards to counts, particularly region counts. When running a 2y build with vcm=92 (this matches old augur) I get the following on `master` (before this PR):
```
Summary of strain counts by category
Categories for segment ha
africa 135
china 209
europe 184
japan_korea 311
north_america 328
oceania 454
south_america 438
south_asia 119
southeast_asia 317
west_asia 597
total 3092
```
Notice that `west_asia` gets a brunch of extra strains. If I instead switch `super_category` to region/year/month as in the PR and set vcm=15 (to get about the same total strains), I get the following much more even distribution:
```
Summary of strain counts by category
Categories for segment ha
africa 184
china 218
europe 240 …
```
=> Subsample by region/year/month

Snakefile, scripts/import_tip_clades.py
Uses the original HA tree used to assign clade memberships to tips to select
only tips when importing clade memberships for other segments. Note that this
commit omits export of any internal node data, since we would not expect
internal node names to match meaningfully between trees for different segments
and auspice can handle missing data for internal nodes gracefully.
Closes #13.
=> Import clade membership using HA tree structure

batch.py
This PR adds a selection flag for segment to the batch submission script for seasonal flu. This gives the user control over all three variables (segment, lineage, resolution) as opposed to just two. Allows re-runs (i.e. for an added outlier) to ignore NA builds, as is often the case.
Defaults to ["ha", "na"].
=> Add selection flag for segment.

Snakefile
This export costs little in time and space, but it enables downstream analyses that depend on amino acid sequences for seasonal flu. For example, auspice JSONs with the root sequence could be used as inputs to forecasts without needing to build new trees just for that purpose.
=> Export root sequences JSON as a standard auspice output

.gitignore, Snakefile, Snakefile_WHO, Snakefile_base, batch.py, scripts/full_region_alignments.py
This is more of an FYI than a request for code review. These are changes to improve scheduling and performance of `--aws-batch` builds. These changes should not impact HPC-based builds. I did a few things here:
1. I made new build-specific "targets" like `targets/flu_seasonal_h3n2_ha_3y` that include the `tree.json`, `meta.json`, etc... so these don't have to be spelled out. I figure this will also be generally convenient.
2. I modified `batch.py` to specify `--aws-batch-cpus` and `--aws-batch-memory` based on number of simultaneous build targets and set snakemake's `--jobs` to correspond.
3. I set `--nthreads 1` to prevent threadlocking (improving AWS Batch builds from 4 hours to 1 hour).
I'm letting AWS Batch handle resource provisioning. This sometimes results in large instances that …
=> Specify batch resources

.travis.yml
The titer TSV was renamed but the Travis script was not updated. This led CI
builds to fail when titers were missing and could not be downloaded from
RethinkDB.
=> Update reference to titer TSV file in Travis config

Snakefile_WHO
This replaces old `_get_mask_config` with a call to `_get_build_distance_map_config` to mimic the behavior of the regular `Snakefile` from https://github.com/nextstrain/seasonal-flu/pull/26.
=> Update WHO builds to work with distance maps.

Snakefile
This is a QOL change since before each new build I had to run additional `rm` commands for the `log` and `data` directories after running `snakemake clean`. This adds those directories to the regular command.
=> Add logs and data directories to clean.

Snakefile, Snakefile_base, config/vaccines_h1n1pdm.json, config/vaccines_h3n2.json, config/vaccines_vic.json, config/vaccines_yam.json
The information, previously exported in `export [v1]` via the auspice config file are stored in dedicated JSON files for `export v2`. The auspice config files remain unchanged so that `export v1` still works as expected, but this information should be removed from them when it's no longer needed.
You will need to use this PR of augur: https://github.com/nextstrain/augur/pull/410
P.S. I don't believe the travis failures are due to this PR, although I only tested it on `3y` builds to speed things up.
=> Vaccine info node-data JSONs

config/frequency_weights_by_region.json
Resolves an issue with KDE frequency weighting where the regions used to weight
frequencies were represented differently in the metadata and the weights
JSON. For example, the metadata contains prettified regions like "North America"
while the weights JSON referred to this region as "north america". This issue
was revealed after introducing code to augur frequencies that eliminated all
unrepresented weight attributes from consideration. When no weights were
represented by the given tips (because of the casing difference shown above),
weighted frequency estimation failed with a ValueError.
[1] https://github.com/nextstrain/augur/pull/420
=> Update region names in frequency weights to match metadata

scripts/global_frequencies.py, scripts/vaccination_coverage.py
This PR fixes the downstream errors in the WHO build due to changes in augur.
1. Ignore the top level `generated_by` key within the frequencies JSON generated by `augur frequencies`.
2. Remove lowering and conversion to snakecase of country names from the static vaccine TSVs, since the metadata now comes in with the country names already "prettified".
=> Update WHO build

Snakefile_WHO, Snakefile_base, Snakefile_report, scripts/age_distributions.py, scripts/flu_regions.py, scripts/full_region_alignments.py, scripts/global_frequencies.py, scripts/graph_frequencies.py, scripts/plot_titer_matrices.py, scripts/scores.py, scripts/select_strains.py
This PR extracts the information on regions that were scattered across multiple scripts into single file `scripts/flu_regions.py`. In addition, this file sources the region weights from config thereby reducing these to one source. 
Working through the different files revealed two problems in our previous graphs
* global frequencies weren't actually region weighted.
* any other resolution then 2y wasn't using the correct alignments for region frequencies.  
I added South Asia to the plots: this corresponds to such a big population that not having it included distorts the picture.
=> Harmonize regions

Snakefile_base
FRA and HINT data have pretty good correspondance so we can combine
them. Download HINT titers along with FRA titers for FRA builds.
Did a test run on AWS (job id `d1976146-60a6-4682-b10b-de2ea3eb1321`)
=> download_titers: Include HINT titers in FRA builds

.travis.yml
Updates the Travis CI environment to use Python 3.9 instead of 3.6. This change addresses two separate issues:
- The default version of pip for Travis's Python 3.9 environment (20.3.1) supports the deterministic dependency resolution required by the Nextstrain CLI installation step that 3.7's pip (20.1.1) does not. See the Travis docs for more details [1].
- Python 3.6 will reach end of life in one month [2].
Python 3.9 was released a year ago and should be entirely reasonable to use as a default now.
[1] https://docs.travis-ci.com/user/languages/python/#new-dependency-resolver-in-pip-203
[2] https://endoflife.date/python
=> CI: Upgrade Python environment

Snakefile, Snakefile_base, config/auspice_config_h1n1pdm.json, config/auspice_config_h3n2.json, config/auspice_config_h3n2_fitness.json, config/auspice_config_vic.json, config/auspice_config_yam.json, config/lat_longs.tsv
Adds "division" as an Auspice color-by, filter, and geographic resolution for all live Nextstrain builds. Updates the lat/longs file from the better ncov workflow version and actually uses this file (which appears to have been unused by the live builds).
Fixes #70
=> Annotate division-level geographic data

Snakefile_base
Given changes in recent circulation patterns of seasonal flu, our
original region-specific weighting is no longer reasonable. For example,
although H3N2 has not been observed in China in over a year, we still
heavily weight the older strains that were observed, giving the
impression in frequency plots that its corresponding genotypes are
actively circulating when they are not. Given that we already perform
region-based subsampling to create our trees, this additional level of
weighting is not worth the noise it adds to the data.
=> Remove weighting of frequencies by region

scripts/select_strains.py
Creating this PR for visibility. 
A quick fix for `select_strains` to skip strains that do not have valid dates. 
Fixes the error that I ran into for today's flu builds:
```
[batch] [Thu Apr 21 17:28:56 2022]
[batch] Error in rule select_strains:
[batch]     jobid: 487
[batch]     output: results/strains_cdc_h1n1pdm_2y_cell_hi.txt
[batch]     shell:
[batch]         
[batch]         python3 scripts/select_strains.py             --sequences results/filtered_h1n1pdm_ha_cell.fasta results/filtered_h1n1pdm_na_cell.fasta             --metadata results/metadata_h1n1pdm_ha.tsv results/metadata_h1n1pdm_na.tsv             --segments ha na             --include config/references_h1n1pdm.txt             --lineage h1n1pdm             --resolution 2y             --viruses-per-month 90 …
```
=> Fix select-strains

Snakefile_WHO
Only run `augur frequencies` for non-empty alignment FASTAs in
rule `complete_mutation_frequencies_by_region`. If alignments for
all genes are empty, then just create an empty frequencies JSON.
Fixes error that arises when `augur frequencies` tries to load
alignments from an empty FASTA file.
Running a full WHO build on AWS Batch (job id `d8e90303-be1d-4bc0-a9e2-0cfb729501a1`)
=> Snakefile_WHO: skip empty region alignments

environment.yaml, scripts/age_distributions.py, scripts/construct-recency-from-submission-date.py, scripts/full_region_alignments.py, scripts/generate_locations_file.py, scripts/scores.py, scripts/select_strains.py
Replaces all uses of `augur.utils.read_metadata` with `augur.io.read_metadata` and uses of `augur.utils.get_numerical_dates` with `augur.dates.get_numerical_dates`. 
The new dates module was introduced in augur 16.0.0 so I also updated the augur dependency in the environment.yaml file.
Related to https://github.com/nextstrain/augur/pull/934 and https://github.com/nextstrain/augur/issues/970
Verified that `select_strains` still ran as expected (not sure how to compare outputs since it's a random subsampling)
Checked the following produce the same outputs before and after change:
- age_distributions
- construct-recency-from-submission-date (only difference is augur version)
- full_region_alignments
- generate_locations_file
- scores
=> Use augur io and dates

zoltar/project.json
Adds a JSON defining the Zoltar [1] project for Nextstrain's seasonal influenza forecasts. The project will be private while we learn how to properly register predictions as part of this workflow. We should eventually be able to automate the submission of predictions as part of our weekly builds.
[1] https://zoltardata.com/
=> Add Zoltar project configuration

Snakefile, Snakefile_WHO, Snakefile_base, Snakefile_countries, scripts/prune_reference.py
Add reference outgroup for 2y and 6m builds to avoid incorrect rooting of trees. The reference is pruned from the tree after the refine step using James' code snippet¹.
The references added are the references used by Nextclade, but with the strain names changed to match the strain name within fauna.
¹ https://github.com/nextstrain/augur/issues/340#issuecomment-545184212
(There's a bunch of path changes, but the main change is in `Snakefile_base`)
Related to https://github.com/nextstrain/augur/issues/340
- Completed a test run of the live builds on AWS Batch (job id: [f059576b-3f9f-413f-9140-e0874e7a67ee](https://us-east-1.console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/f059576b-3f9f-413f-9140-e0874e7a67ee))
- Deployed test run builds to …
=> Add reference outgroup for 2y/6m builds

scripts/entropy.py
Starting with Docker image nextstrain/base:build-20221201T013147Z, the WHO flu builds began to fail at the rule `export_entropy` with the following error:
```
Traceback (most recent call last):
File "/nextstrain/build/scripts/entropy.py", line 64, in <module>
entropy[gene] = calc_entropy(calc_SNV_frequencies(MultipleSeqAlignment(seqs), alphabets['aa']),
File "/nextstrain/build/scripts/entropy.py", line 22, in calc_entropy
res['pos'] = [int(x) for x in start + (3 if aa else 1)*np.arange(af.shape[1])]
File "/usr/local/lib/python3.10/site-packages/Bio/SeqFeature.py", line 2109, in __add__
return self.__class__(int(self) + offset)
File "/usr/local/lib/python3.10/site-packages/Bio/SeqFeature.py", line 2095, in __new__
return int.__new__(cls, position)
TypeError: only size-1 arrays can be …
```
=> Fix export_entropy rule: convert start to int

Snakefile_base
This is a short term solution to getting the WHO running again as `augur frequencies` was running into an error where the root cause is pandas.date_range was not producing the date range we expected.¹
This change can be reverted once the underlying bug in augur has been resolved.
¹ https://bedfordlab.slack.com/archives/C03KWDET9/p1673039234734289
---
I'm running the WHO build with this change on AWS Batch (`370bfb5f-78cc-4bc0-9845-8a5d7fbd55bd`) and will merge this once that has completed successfully.
=> max_date: Add an extra month to today's date

config/clades_h3n2_ha.tsv
there was some ambiguity how short the short clades should be. the CCs prefer even shorter names.
=> adjust h3n2 clade shortnames

config/h3n2/ha/clades-long.tsv, config/h3n2/ha/emerging_clades.tsv
when moving to a different reference, the h3n2 nucleotide coordinates needed to be changed. this was already in place for the `config/h3n2/ha/clades.tsv`, but not the `clades-long` and emerging variants file.
=> fix: shift nucleotide coordinates for h3n2 clade files

.github/workflows/run-private-nextflu-builds.yaml, .github/workflows/run-public-builds.yaml, .github/workflows/upload.yaml
Add option to trigger builds after the uploads to S3 have completed.
The downstream triggers are optional, so we can still run upload jobs without starting builds. 
I kept the builds as separate GH workflows so that they can also be run independently of the upload job. 
There's a lot of overlap in the public and private build workflows (as well as with all the other AWS Batch workflows across all of our pathogen repos). Hopefully will be able to trim them down after we set up a reusable workflow for these jobs. 
Still need to manually download the builds from AWS Batch and deploy them. I haven't set up any auto-deployments or Slack messages (yet).
=> Automate builds

.github/workflows/upload.yaml, profiles/upload/upload.smk
Updates the "upload" profile's custom rules to support uploading parsed sequences (per lineage and segment) and metadata (per lineage) and updates the "upload" GitHub Action to request these new targets for the workflow.
Resolves #107
=> Add rules to upload parsed sequences and metadata

workflow/snakemake_rules/core.smk
Use stochastic polytomy resolution instead of greedy to avoid caterpillar like trees.
=> use stochastic polytomy resolution

README.md
Refactoring the workflow changed organization of the repo and the Snakemake arguments used to run the builds. This commit updates the docs in the README to match the refactored workflow and uses the CI build as an example workflow for external users.
Motivated by https://github.com/nextstrain/seasonal-flu/issues/112.
=> Update README for refactored workflow

.github/workflows/run-private-nextflu-builds.yaml, .github/workflows/run-public-builds.yaml, .github/workflows/upload.yaml
Simplify build workflows by using the reusable Nextstrain pathogen-repo-build workflow.
=> Use pathogen-repo-build workflow for builds

.github/workflows/run-public-builds.yaml, profiles/nextstrain-public.yaml, profiles/nextstrain-public/deploy.smk
Deploy the public builds to s3://nextstrain-data as part of the automated public workflow. 
The public builds should no longer have to be manually inspected since outliers are now automatically removed as of #110. 
Follow up to #106
=> Auto deploy public builds

Snakefile, profiles/scicore/submit.sh
The AUGUR_RECURSION_LIMIT is set to 10,000 by default since Augur 22.0.0 and the workflow's minimum required Augur version is now 22.0.2¹
¹ https://github.com/nextstrain/seasonal-flu/blob/65df51732abcad6480239fb0c7e76e47ae5c9723/workflow/envs/nextstrain.yaml#L7
=> Remove AUGUR_RECURSION_LIMIT

.github/workflows/run-private-nextflu-builds.yaml, .github/workflows/run-public-builds.yaml, .github/workflows/upload.yaml
Better to be explicit about which envvars are being passed to runtimes rather than rely on the automatic variables passed through.
The upload workflow requires the rethinkdb secrets to access Fauna and the AWS secrets to upload files to S3.
The public and private builds just need the AWS secrets to launch jobs on AWS Batch and to download files from S3.
These are all GitHub Action secrets that are being inherited by the reusable workflow and available as envvars in the GitHub Action job.
Follow up on https://github.com/nextstrain/seasonal-flu/pull/111, following @tsibley's [recommendation](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1692833620772029?thread_ts=1690498985.056099&cid=C01LCTT7JNN) to be explicit about envvars.
=> Update builds to use `--env` options

scripts/flag_outliers.py, workflow/snakemake_rules/core.smk
Adds an argument to the script for flagging outliers that accepts a file with a list of strains to keep in the output tree even if they are outliers and updates the core workflow logic to use this argument whenever builds define a list of strains to force-include. This change fixes a bug when older titer reference strains (e.g., A/Wisconsin/588/2019 for H1N1pdm) get flagged as outliers in the tree and dropping them causes downstream titer analyses to fail. Our choice to force-include these strains in the build should override the automated outlier detection.
=> Keep reference strains in tree even if they are outliers

.github/workflows/deploy-private-nextflu.yaml
The private.nextflu.org site is still built using the old Auspice
version in https://github.com/blab/nextflu and deployed to Netlify.
This requires an older version of Ruby (2.3.7) and dependencies that
others have had trouble installing on the new M1 macs. Instead of
depending on my old mac to deploy the private builds, use a GitHub
Action workflow  to deploy the site that anyone on the Nextstrain team
can run.
I've opted for this route instead of trying to update the dependencies
for the old Auspice because the ultimate goal is to sunset the private
site. This seemed like less work than fiddling with dependencies.
> [!NOTE]  
> For this new workflow, I had to add [ruby/setup-ruby@v1](https://github.com/ruby/setup-ruby) to the Nextstrain's list of allowed actions.
This can be run …
=> Deploy private nextflu builds to Netlify

.github/workflows/deploy-private-nextflu.yaml
Pin Netlify CLI version for now to get the deployment of the private nextflu site working. 
When I went to login to the private site after deployment today, the username and password did not work as expected. 
I compared [this weeks deployment](https://github.com/nextstrain/seasonal-flu/actions/runs/6907038759/job/18793376743#step:10:11) to [last week's deployment](https://github.com/nextstrain/seasonal-flu/actions/runs/6853790956/job/18635385696#step:10:11) and saw a change in the Netlify CLI version from 17.2.2 to 17.5.1. 
I did [a test run with the Netlify CLI pinned to 17.2.2](https://github.com/nextstrain/seasonal-flu/actions/runs/6908500166) and the staging site was working as expected.
=> Fix deploy private

profiles/nextflu-private/README.md, profiles/nextflu-private/antigenic_distances.smk, profiles/nextflu-private/report.smk, scripts/count_recent_tips_by_clade.py, scripts/summarize_haplotype_titer_coverage.py, workflow/envs/nextstrain.yaml
Adds Snakemake rules and scripts to make Markdown tables as part of the nextflu-private workflow, so we can add these tables to our monthly reports.
The functionality from this PR depends on [the tabulate package](https://pypi.org/project/tabulate/). This package gets installed implicitly in Nextstrain Docker and Conda runtimes as a dependency of Snakemake, however we will want to eventually install tabulate in those runtimes explicitly to document that we depend on it directly. [See this Slack thread for more details](https://bedfordlab.slack.com/archives/C03KWNCLK/p1686327885597899?thread_ts=1686324517.672459&cid=C03KWNCLK).
=> Make Markdown output for reports

config/h3n2/na/genemap.gff
Including such information will become mandatory in Augur following <https://github.com/nextstrain/augur/pull/1351>.
Segment length from <https://www.ncbi.nlm.nih.gov/nuccore/CY114383>
This absence was noticed by [this failing CI action](https://github.com/nextstrain/augur/actions/runs/7107634336/job/19349457899) on the [above augur PR](https://github.com/nextstrain/augur/pull/1351)
=> Add h3n2/na segment length to GFF

config/h1n1pdm/auspice_config.json, config/h3n2/auspice_config.json, config/vic/auspice_config.json, config/yam/auspice_config.json
Adds coloring entries for the HA and NA accessions associated with each sequence in a build, so this information appears in the public trees and allows users to determine the sequences that correspond with each strain name.
Closes #137
=> Add Auspice JSON colorings for HA/NA accessions

workflow/snakemake_rules/report.smk
Soon we will release nextclade v3. Once nextclade v3 hits bioconda, workflows that rely on v2 syntax will break. To prevent this, this PR makes it explicit that the syntax used is for v2 and that the v2 binary nextclade2 should be used.
This binary is in both the nextstrain-base docker image and in the conda-base managed conda environment.
Users who don't use either will have to add nextclade2 to the path.
Over the next few weeks, we will transition repos to use nextclade3. The reason to add nextclade2 now is so that workflows don't break if they haven't yet transitioned to nextclade3 at the time of v3 release. It also makes it easy to search which workflows need to be changed.
=> Version nextclade binary for transition, i.e. nextclade -> nextclade2

README.md
The `nextstrain build` command should be the same regardless of which runtime the user has installed as the default.
Snakemake's `--use-conda` flag also causes an error when used with the Nextstrain managed Conda runtime as described in
https://github.com/nextstrain/seasonal-flu/issues/149
=> GISAID Quickstart: remove Conda runtime specific command

.github/workflows/upload.yaml
Adds an option to the "upload" GitHub Action to trigger nextflu-private group builds when the upload action completes successfully.
Related to #130
=> Trigger nextflu-private builds from upload action

.github/workflows/run-nextclade.yaml, Snakefile, profiles/nextclade.yaml, profiles/nextclade/run-nextclade.smk, workflow/snakemake_rules/core.smk, workflow/snakemake_rules/download_from_s3.smk, workflow/snakemake_rules/export.smk
Adds rules, config, and GitHub Action file to support running Nextclade on all available HA and NA sequences for H1N1pdm, H3N2, and Vic.
The new Snakemake logic lives in a custom build config named `nextclade` which skips most of the standard workflow build logic, using only the "download from S3" rules and its own custom rules to run Nextclade for the lineages and segments defined in the build config. This custom logic runs Nextclade with the default dataset per lineage and segment [just like the flu_frequencies workflow](https://github.com/nextstrain/flu_frequencies/blob/6e4298fac3361f4a6751d85bcb963064dbb9eee1/Snakefile#L89-L960) and uploads the results to S3. Once we have merged this PR, we should be able to automatically run Nextclade with each ingest of new data and run …
=> Add GitHub Action for Nextclade annotations

profiles/upload.yaml
Adds the field containing GISAID isolate id (values prefixed by "EPI_ISL_") to the list of fields to include in the download from fauna in the "upload" configuration file. When we run the upload workflow with this change, the parsed metadata files on S3 should include the new column without any other changes needed by other workflows that download the data from S3.
This isolate id field is important in that it represents a single viral isolate that has one or more segment accessions for genes like HA, NA, etc.
=> Add isolate_id field to metadata

profiles/nextstrain-public-yamagata.yaml, profiles/nextstrain-public.yaml
We will be changing the URLs for seasonal flu from `nextstrain.org/flu/seasonal/...` to `nextstrain.org/seasonal-flu/...` to match changes for avian-flu.
This commit changes the build_name and auspice_name for the nextstrain-public builds to reflect this change.
Resolves #152
=> profiles/nextstrain-public: Update build/auspice names

.github/workflows/upload.yaml
Updates the upload GH Action workflow to use a matrix to define downstream triggers after upload job is complete. 
Also adds the `run-nextclade.yaml` workflow to the matrix of triggers for the upload workflow.
Follow up to https://github.com/nextstrain/seasonal-flu/pull/158
=> Upload trigger matrix

.github/workflows/run-nextclade.yaml, .github/workflows/run-nextflu-private-builds.yaml, .github/workflows/run-private-nextflu-builds.yaml, .github/workflows/run-public-builds.yaml, .github/workflows/upload.yaml
I'll also be removing the corresponding repository secrets.  Both that and this commit are required to effect the switch for the workflows using our AWS Batch runtime, which is all of them except upload.yaml. _That_ workflow will be switched solely by the removal of repository secrets, with the change to it here merely a cleanup.
Related-to: <https://github.com/nextstrain/private/issues/110>
=> Switch AWS credentials from a long-lived IAM user to short-lived role sessions

.github/workflows/deploy-private-nextflu.yaml
Assumes the GitHubActionsRoleNextstrainBatchJobs role to get short-lived credentials for the workflow to have access to download build from AWS Batch.
Depends on https://github.com/nextstrain/infra/pull/19
Related to https://github.com/nextstrain/private/issues/110
=> deploy-private-nextflu: Assume AWS role for short-lived credentials

.gitignore, .pylintrc, profiles/nextflu-private/report.smk, scripts/add_derived_haplotypes.py, scripts/annotate_haplotypes.py, scripts/count_recent_tips_by_clade.py, scripts/estimate_frequencies_from_metadata.py, scripts/summarize_haplotypes.py
Replaces the current table of derived haplotype frequencies and titer references that is based on a subsampled HA tree with a table based on all available sequences during the same time period.
With the latest version of Nextclade, we can determine derived haplotype strings per record from a Nextclade annotations file with columns for clade and mutations relative to each clade. We can then calculate haplotype frequencies from all available data instead of a subset of data used to build a tree.
Related to #130
Depends on https://github.com/nextstrain/nextclade/pull/1492
=> Summarize haplotype coverage by titer references using frequencies per haplotype from all available data

config/h1n1pdm/auspice_config.json, config/h3n2/auspice_config.json, config/vic/auspice_config.json, profiles/ci/builds.yaml, profiles/nextflu-private.yaml, profiles/nextflu-private/h1n1pdm/ha/auspice_config.json, profiles/nextflu-private/h1n1pdm/na/auspice_config.json, profiles/nextflu-private/h3n2/ha/auspice_config.json, profiles/nextflu-private/h3n2/na/auspice_config.json, profiles/nextflu-private/vic/ha/auspice_config.json, profiles/nextflu-private/vic/na/auspice_config.json, profiles/nextstrain-public.yaml, scripts/intersect_items.py, scripts/table_to_node_data.py, workflow/envs/nextstrain.yaml, workflow/snakemake_rules/core.smk, workflow/snakemake_rules/export.smk
Adds logic and scripts to the core workflow to create a t-SNE embedding per build with all segments and create HDBSCAN clusters from the embeddings. Updates the Auspice config JSONs the public and private builds to include the new t-SNE coordinate fields and the t-SNE cluster field.
Although we select the same strains for each gene segment, not all segment sequences can be aligned. As a result, different sets of strains can appear in the final Nextclade alignment for each gene segment. Since the t-SNE embedding requires the same strains to be present for all of its inputs and in the same order, we need to find the list of strains shared across all segments, extract only those strain sequences from each segment alignment, and sort the alignments prior to calculating pairwise distances and …
=> Add t-SNE embeddings and clusters to workflow

config/h1n1pdm/ha/auspice_config.json, config/h1n1pdm/na/auspice_config.json, config/h3n2/ha/auspice_config.json, config/h3n2/na/auspice_config.json, config/vic/ha/auspice_config.json, config/vic/na/auspice_config.json, profiles/nextflu-private.yaml, profiles/nextstrain-public.yaml
Adds segment-specific Auspice config JSONs for 2y builds of H1N1pdm, H3N2, and Vic with custom color scales for subclades within each subtype and segment. These color scales match the scales used in the nextflu-private builds, allowing us to include the public trees in our monthly reports and easily switch between private and public trees without changing color schemes across builds.
With this change, we can remove the "representative" builds from the nextflu-private build config, since the public builds already provide equal geographic and temporal sampling.
Closes #164
=> Add segment-specific Auspice configs for 2y builds

Snakefile, config/h3n2/ha/auspice_config.json, nextclade/config/config_dict.yaml, profiles/nextflu-private-forecasts.yaml, profiles/nextflu-private.yaml, profiles/nextflu-private/h1n1pdm/ha/auspice_config.json, profiles/nextflu-private/h3n2/ha/auspice_config.json, profiles/nextflu-private/vic/ha/auspice_config.json, profiles/nextstrain-public.yaml, workflow/snakemake_rules/core.smk, workflow/snakemake_rules/export.smk, workflow/snakemake_rules/fitness.smk
Adds rules and configs to annotate emerging subclades to nextflu-private builds, paving the way for any builds that define the `emerging_subclade` path in their config to use the same clade definitions. Most of these emerging subclades map directly to the main branch in the corresponding influenza nomenclature repos. H3N2 HA is an exception where the definitions come from a branch called `emerging`.
=> Add emerging subclades to nextflu-private builds

nextclade/Snakefile, profiles/upload.yaml
The fields to export in acknowledgements is hardcoded in Auspice¹ so the
metadata field needs to be named `gisaid_epi_isl` to be included in
the acknowledgements for the seasonal flu builds. Renaming the column
in our upload config to avoid having to rename it as part of the
phylogenetic workflow.
¹ <https://github.com/nextstrain/auspice/blob/dae78e74d5e06303d901387adf9fe7550a7d4aa9/src/components/download/helperFunctions.js#L326>
First step for https://github.com/nextstrain/seasonal-flu/issues/178
=> Rename metadata column from `isolate_id` to `gisaid_epi_isl`

config/h1n1pdm/auspice_config.json, config/h1n1pdm/ha/auspice_config.json, config/h1n1pdm/na/auspice_config.json, config/h3n2/auspice_config.json, config/h3n2/auspice_config_fitness.json, config/h3n2/ha/auspice_config.json, config/h3n2/na/auspice_config.json, config/vic/auspice_config.json, config/vic/ha/auspice_config.json, config/vic/na/auspice_config.json, config/yam/auspice_config.json
Temporarily dropping `gisaid_epi_isl` after discussion on Slack¹ about the duplicate accessions we are seeing with cell/egg passaged sequences. Once we update the data model to accurately link virus record and sequence record, we can add it back.
¹ <https://bedfordlab.slack.com/archives/C03KWDET9/p1729271930916079>
Follow up to https://github.com/nextstrain/seasonal-flu/pull/180
Related to https://github.com/nextstrain/fauna/issues/165
=> Remove `gisaid_epi_isl` from auspice_config JSONs

profiles/nextclade.yaml, profiles/nextclade/run-nextclade.smk
Adds remaining gene segments to the default list of segments to process with Nextclade. Since B/Vic only has HA and NA Nextclades datasets right now, this commit modifies the logic of the workflow to look for a build-specific list of segments and defines that list for the Vic build.
Follows from #183
=> Run Nextclade on all 8 genes for H1 and H3

config/h1n1pdm/ha/auspice_config.json, config/h1n1pdm/na/auspice_config.json, config/h3n2/ha/auspice_config.json, config/h3n2/na/auspice_config.json, config/vic/ha/auspice_config.json, config/vic/na/auspice_config.json, profiles/nextflu-private-forecasts.yaml, profiles/nextflu-private.yaml, profiles/nextflu-private/h1n1pdm/ha/auspice_config.json, profiles/nextflu-private/h1n1pdm/na/auspice_config.json, profiles/nextflu-private/h3n2/ha/auspice_config.json, profiles/nextflu-private/h3n2/na/auspice_config.json, profiles/nextflu-private/vic/ha/auspice_config.json, profiles/nextflu-private/vic/na/auspice_config.json, profiles/nextstrain-public-yamagata.yaml, profiles/nextstrain-public.yaml, profiles/private.nextflu.org.yaml, profiles/upload.yaml
=> Include original GISAID strain name in metadata

nextclade/config/auspice_config.json, nextclade/config/config_dict.yaml, nextclade/dataset_config/h1n1pdm/includes.txt, nextclade/scripts/merge_jsons.py
- Adds a 6B.1A.4 strain to list of strains to be force included in the Nextclade datasets for H1 HA trees.
- Renames `proposed_clade` to `proposed_subclade` to clarify that the values are consistent with the newer subclades. Uses the underscore delimiter to be consistent with most other annotations in the flu builds (e.g., `num_date`, `ne_star`, `submitting_lab`, etc.).
Related to b09a5019316203ef2463a6da741db01cc7c2d140
Required for https://github.com/nextstrain/nextclade_data/pull/236
Required for #193
=> Refine proposed subclades in Nextclade datasets

config/h1n1pdm/auspice_config.json, config/h1n1pdm/ha/auspice_config.json, config/h1n1pdm/na/auspice_config.json, config/h3n2/auspice_config.json, config/h3n2/ha/auspice_config.json, config/h3n2/na/auspice_config.json, config/vic/auspice_config.json, config/vic/ha/auspice_config.json, config/vic/na/auspice_config.json, profiles/ci/builds.yaml
Adds Nextclade extension with "subclade" annotation to Auspice config for all public builds, allowing users to get these subclade annotations from Nextclade for any public tree.
To test this functionality, I added subclade annotations to the CI build and confirmed that the extension worked as expected by uploading [the CI Auspice JSON to the staging server](https://nextstrain.org/staging/ci/build/ha) before and after I included the extension in the JSON.
=> Add Nextclade extension to public builds

config/lat_longs.tsv
Fixes https://github.com/nextstrain/seasonal-flu/issues/155
Interestingly, we don't have any entries for "Suffolk" in the fauna/source-data/geo_synonyms.tsv¹ and I couldn't find any metadata in our private S3 bucket that includes "Suffolk" as a location.
¹ https://github.com/nextstrain/fauna/blob/75e309e9afe2cc97fb56d7a24e22a07b698805bf/source-data/geo_synonyms.tsv
=> Update Suffolk lat/longs

workflow/snakemake_rules/select_strains.smk
Adds a new `gihsn_sample` column to the metadata to indicate whether
"GIHSN" was found in the `strain` as proxy for whether the sample came
from the Global Influenza Hospital Surveillance Network (GIHSN).
Follows the existing pattern of using `True` and `False` boolean values.
Resolves <https://github.com/nextstrain/seasonal-flu/issues/196>
=> Add rule to annotate GIHSN samples

workflow/snakemake_rules/download_from_fauna.smk
The latest upload workflow¹ seemed to overwhelm the rethinkdb server so limiting concurrent fauna connections to see if it would prevent the OOM error.
Use of Snakemake's `workflow.global_resources` inspired by the ncov use to limit concurrent deploy jobs.² Doing this instead of limiting the overall number of Snakemake jobs with `-j` because there are other rules in the workflow that can run without connections to fauna.
¹ <https://github.com/nextstrain/seasonal-flu/actions/runs/12715154181/job/35446799658> 
² <https://github.com/nextstrain/ncov/blob/20f5fc3c7032f4575a99745cee3238ecbeebb6e0/workflow/snakemake_rules/export_for_nextstrain.smk#L340-L362>
=> Limit concurrent fauna connections to 2

config/h3n2/reference_strains.txt, config/h3n2/vaccine.json, config/references_for_titer_plots/h3n2/cell_fra.txt, config/references_for_titer_plots/h3n2/cell_hi.txt
As part of clean up in https://github.com/nextstrain/fauna/issues/174, the strain name "A/DistrictofColumbia/27/2023" has been updated to "A/DistrictOfColumbia/27/2023" to follow our standard capitalization of DC in strain names.
Removed the now duplicate entries from references_for_titer_plots.
=> Update DistrictofColumbia/27 to DistrictOfColumbia/27

.github/workflows/upload.yaml
Prevent multiple upload GH Action workflows from running so that they can't overwhelm Fauna. Cancels in progress workflow if the triggered workflow is running on the default branch to prioritize new uploads after manual ingest.
Prompted by recent back to back upload workflows [[1](https://github.com/nextstrain/seasonal-flu/actions/runs/12955578776), [2](https://github.com/nextstrain/seasonal-flu/actions/runs/12956817347)].
=> Add concurrency restriction to upload GH Action

narratives_template/nextstrain-cdc.md.jinja, profiles/nextflu-private/report.smk, scripts/create_narrative.py, workflow/envs/nextstrain.yaml
Adds a script to load a Markdown template written in [Jinja2 syntax](https://jinja.palletsprojects.com/en/stable/templates/) and write out a narrative stub with the correct dates in the narrative frontmatter and the Nextstrain URLs. The included Markdown template assumes that the narrative will be written to a `narratives/path.md` path with images in the same repo's `figures/` directory.
This PR also adds a rule to run this script from the workflow to automate narrative creation during the nextflu-private builds. We could optionally upload the narrative stub to the desired Nextstrain Group, in the future, but for now this implementation will allow us to quickly get a new report going without manually updating dates or markdown tables.
Note that Jinja2 is available in the base Nextstrain …
=> Add script and template to automate narratives

.github/workflows/run-nextclade.yaml, .github/workflows/upload.yaml
Adds a job to the upload GitHub Action to run Nextclade on all sequences before triggering downstream workflows. This change ensures that Nextclade annotations in S3 reflect the latest data when other workflows run. This commit removes the option to trigger the separate Nextclade GHA from the upload action. Thanks to @tsibley, this implementation reuses the Nextclade GHA, so we can still manually trigger just that action later when we need to.
=> Run Nextclade in GHA for uploads

config/distance_maps/README.md
Add citations for the epitope of map sites in a top-level README file, listed in chronological order of publication. I put them in a table, split by type and gene, but feel free to reword or suggest a different format.
Eventually, based on [a slack thread](https://bedfordlab.slack.com/archives/C03KWDET9/p1743617647803209?thread_ts=1743617294.221779&cid=C03KWDET9), we may want to switch to adding these as DOI keys in the top-level JSON.
I wasn't confident I could safely add new keys to the JSON files without breaking something in the workflow, hence the README docs for now.
=> Add citations for epitope or map sites

profiles/nextstrain-public.yaml
Noticed by @j23414 during testing with the new ingest results that there were warnings about the `passage` column not existing in the metadata.
Turns out this is a warning we also see in the prod builds because we do no have a `passage` column in our current metadata.
<https://github.com/nextstrain/seasonal-flu/actions/runs/14648450833/job/41108380205#step:5:2695>
=> profiles/nexstrain-public: Remove filter `--exclude-where passage=egg`

ingest/scripts/annotate-with-passage-category
Somehow missed the line in the fauna code that used the uppercase for passage.
<https://github.com/nextstrain/fauna/blob/fbdc393581b1859ac817403d8f43e114d7edbc60/vdb/flu_upload.py#L417>
Follow up on https://github.com/nextstrain/seasonal-flu/pull/218
=> ingest/annotate-with-passage-category: Fix mismatch due to casing

ingest/defaults/config.yaml, ingest/rules/curate.smk, ingest/scripts/parse-gisaid-location, ingest/scripts/standardize-lineage, ingest/scripts/standardize-strain-names
Updates to the ingest workflow that I made as I compared the trial outputs with the fauna metadata.
There are still geolocation updates that need to be made that I will address separately. 
One missing chunk of data are B types that are missing "Lineage" from GISAID, so they cannot be classified as vic or yam. I'm not sure how they were originally labelled as vic or yam in fauna. This might be a future improvement where we run Nextclade in the ingest workflow to classify them rather than rely on the GISAID labels.
=> Ingest updates

profiles/allflu/config.yaml, profiles/example/config.yaml, profiles/nextstrain/config.yaml
Excludes the cluster profiles `hutch` and `scicore` because it's unclear what version of Snakemake is used for those clusters.
Part of #238
=> Update profiles to be compatible with Snakemake v9

CHANGES.md, profiles/full-trees.yaml, workflow/snakemake_rules/core.smk
Adds a top-level parameter to configure the local clock filter's z-score cutoff. Sets the cutoff to a very high value for the "full" builds to prevent most sequences from being dropped for this local clock reason.
=> Parameterize the local clock filter cutoff

CHANGES.md, config/h1n1pdm/reference_strains.txt, config/h1n1pdm/vaccine.json, config/h3n2/reference_strains.txt, config/h3n2/vaccine.json
Adds SH 2025 vaccine strains for H1 and H3 to the vaccines JSONs and reference strains list.
Closes #255
=> Add SH 2025 vaccine strains
